### ISSUE TITLE
1.2 version does not recognize pyproject.toml robotidy settings 

### ISSUE THREAD

**Issue by kstine** [MarketSquare/robotframework-tidy#138]
Unless I am reading the documentation incorrectly this is the toml file I am using for configuring my robotidy:

[tool.robotidy]
diff = true
overwrite = true
configure = [
    "AlignSettingsSection:spacecount=2",
    "DiscardEmptySections:allow_only_comments=True",
    "NormalizeAssignments:equal_sign_type=remove",
    "NormalizeNewLines:section_lines=3",
    "NormalizeNewLines:test_case_lines=1",
    "NormalizeNewLines:keyword_lines=1",
    "NormalizeNewLines:consecutive_lines=0",
    "NormalizeSectionHeaderName:uppercase=false",
    "NormalizeSeparators:spacecount=2",
    "NormalizeSettingName",
    "ReplaceRunKeywordIf",
    "SplitTooLongLine:split_on_every_arg=false",
    "SplitTooLongLine:line_length=120"
]

My command I am using is: robotidy --spacecount 2 --config pyproject.toml <Path to File>

I have tried both configure and transform. Maybe there is a setting I am not following.

BTW Python 3.7.9 Windows 10

**Comment by bhirsz** [comment]
Do you provide source paths as well? It wasn't so clear before and in 1.2.0 if you run robotidy without providing any paths (ie ``robotidy --someoption 4`` instead of ``robotidy --someoption 4 .`` or `` robotidy source.robot`` it would not do anything. In future release (1.3.0) it is printing the warning. 

Also I see you're using spacecount both globally and as argument to AlignSettingsSection -> this option is only supported as global option (so it's enough to run ``--spacecount 2``). 

There could be also misconception how --transform and --configure works. By default robotidy runs all transformers that don't have 'disabled' tag printed when you run ``robotidy --list``. If you wish to configure some of those transformers you could run:
```
robotidy --transform SomeTransformer:param_name=param_value source.robot
```
or inside toml:
```
configure = [
    SomeTransformer:param_name=param_value
]
```
If you want to run only selected transformers, for example transformerA and transformerB you need to use ``--transform``:
```
robotidy --transform transformerA --transform transformerB source.robot
```
as matter of convenience you can configure such transformers in two ways, either:
```
robotidy --transform transformerA:param_name=value source.robot
```
or
```
robotidy --transform transformerA --configure transformerA:param_name=value source.robot
```
I'm mentioning it because I see that you have transformers without configuration inside your configure. 

I will run tests with your configuration - I see that there are possible problems, especially because I mostly tested it with chained configurations (NormalizeNewLines:section_lines=3:keyword_lines=1 instead of listing it separatetly). Your way is fine and it should work - but I need to test it throughly.

**Comment by bhirsz** [comment]
I've tested and there is bug - it only appears when loading with --config option, autodetected configuration works fine. I'll take care of it.
