### ISSUE TITLE
robotidy produces a lot of command line output by default

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-tidy#162]
We are running robotidy as part of robotframework-browser pre-commit hooks.
Currently robotidy will write lines such as:
`Transforming ../robotframework-browser/atest/test/01_Browser_Management/switching_browsers.robot file`
for each file it touches although it does not make any changes. In our case this is around 40 of lines.
Could default output be less verbose? Only show files that get changed?

**Comment by bhirsz** [comment]
By default robotidy does not print anything when transforming files. This line "Transforming.." is printed only when verbose option is on. There is possiblity that the config is not parsed correctly and that's why you have verbose option set unintentionally. Can you provide your configuration file / or cli options you're using so I can check?

**Comment by mkorpela** [comment]
Sorry. My bad. @bhirsz did not notice the `-v` option in the command.
