### ISSUE TITLE
Consider sorting remote libraries Outside list of default libraries

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-tidy#175]
Hello !

After applying robotidy on my robot files I was left with the following file:

```
*** Settings ***
Library     Collections
Library     DateTime
Library     Dialogs
Library     OperatingSystem
Library     Remote    http://localhost:9050/    WITH NAME    JDBCDB2    # DB2
Library     String
Library     XML
Library     Browser
Library     RequestsLibrary
Library     Keywords/MyUtilities.py
Resource    Setup_-_Teardown/Setup.robot
Resource    Setup_-_Teardown/Teardown.robot
```

A so called "remote" library was in between the internal Libraries.
Would it be possible to sort remote libraries after the internal and external libraries ?

I assume the sorting is now something like:
1) Sort all internal known libraries
2) Sort all unknown libraries
3) Sort resources

If not, I don't understand why Browser and RequestLibrary are not sorted correctly !

Thanks in advance

**Comment by bhirsz** [comment]
Current sort order is:
1. Built in libraries first (Collections, DateTime and such)
2. Any other libraries - in order it was found in file
3. Resources
4. Variables

The reason why your remote library moved to the middle is because "Remote" is also built in library. In your case:
```
Library     Collections
Library     DateTime
Library     Dialogs
Library     OperatingSystem
Library     Remote    http://localhost:9050/    WITH NAME    JDBCDB2    # DB2
Library     String
Library     XML  # up to there we have built in libs
Library     Browser  # it's not built in, so goes there
Library     RequestsLibrary
Library     Keywords/MyUtilities.py
```
I agree though it's not that fortunate - I can exclude Remote from this behaviour (so it will stay in the order you have it already, be it last of libraries).

But since people reported that Robotidy tend to break their test due to sorting imports, starting from the next release Robotidy by default with preserve the order of imports (that can be changed to work as before). From next version in order to order imports you will need to add this configuration:
```
--configure OrderSettingsSection:imports_order=library,resource,variables
```

**Comment by bhirsz** [comment]
Implemented proposal in linked PR - see source / expected file from atests.

**Comment by emakaay** [comment]
@bhirsz 
This solution is fine for me (it's only a minor issue anyway).
When do you expect a new version to be released ?

**Comment by bhirsz** [comment]
@emakaay 
By tommorow latest
