### ISSUE TITLE
tests that use templates are formatted wrong

### ISSUE THREAD

**Issue by DetachHead** [MarketSquare/robotframework-tidy#185]
before:
```robot
*** Settings ***
Test Template       bar

*** Test Cases ***      baz         qux
test1                   hi          hello
test2 long test name    asdfasdf    asdsdfgsdfg

*** Keywords ***
bar
    [Arguments]  ${baz}  ${qux}
```
after:
```robot
*** Settings ***
Test Template       bar

*** Test Cases ***    baz    qux
test1    hi    hello
test2 long test name    asdfasdf    asdsdfgsdfg

*** Keywords ***
bar
    [Arguments]    ${baz}    ${qux}
```

**Comment by bhirsz** [comment]
@DetachHead 

Linked PR with `AlignTestCases` transformer that will align templated test case. Since it's quite tricky subject and you could have code that I don't expect (Robot Framework is too flexible sometimes :) ) it's non default transformer for time being. Meaning that after next release you will be able to run it by configuring it:
```
robotidy --configure AlignTestCases:enabled=True <src>
```

Please give your feedback if there are any issues after next release. In the future this transformer should also support aligning not templated test cases (or templated with [Template] rather than Test Template).

**Comment by DetachHead** [comment]
@bhirsz thanks for the fix. i did find an issue however where if the test names are on a different line to the arguments it screws up #207
