### ISSUE TITLE
[Transformer] Add transformer for ordering tags

### ISSUE THREAD

**Issue by adrszad** [MarketSquare/robotframework-tidy#205]
Add transformer for ordering tags in test cases and keywords, it should:

1. be non default
2. allow to sort case sensitively/insensitively, optionally in reverse order

Optional features to consider:
1. support custom sorters
2. configure keyword and test case order separately

**Comment by bhirsz** [comment]
It's actually really good idea to have consistent tagging. What about doing extra cleaning on tags - like removing duplicates, normalizing names.

**Comment by adrszad** [comment]
> It's actually really good idea to have consistent tagging! What about doing extra cleaning on tags - like removing duplicates, normalizing names?

Yeah, these would be useful as well, as a separate transformers or somewhere here?

**Comment by bhirsz** [comment]
Since it's "OrderTags" I think it's better to stick to just ordering them. We could add new transformer, ie "NormalizeTags" or whatever that would do above (and it would be default one). With extra option "common_to_force_tags" (temporary name) that would move tags that are repeated in every test case to Force Tags. 

Regarding supporting custom orderers, do you have any idea on implementation? It's bit tricky. Simplest implementation would be evaluating passed string (but also dangerous)

**Comment by adrszad** [comment]
I'll add this NormalizeTags transformer.

Regarding this custom sorter, here's some poc:
```
import sys
import importlib.machinery
path = sys.argv[1]
name = "sorter_module"
loader = importlib.machinery.SourceFileLoader(name, path)
sorter_module = loader.load_module()
print(sorted([1,2,3], key=sorter_module.sorter))

# run this scripty with like this: python example.py path_to_custom_sorter.py

# custom_sorter.py content:

# def sorter(item):
#     reversed = item * -1
#     return reversed

# stoudt from example.py:
# [3, 2, 1]
```

**Comment by bhirsz** [comment]
@adrszad I have merge the code and I will create release tommorow. Do you think we can close this issue? (we can create another one if we want to extend this transformer)
