### ISSUE TITLE
Add option to disable ANSI color codes in diff

### ISSUE THREAD

**Issue by DrVanScott** [MarketSquare/robotframework-tidy#268]
As click seems not to support this globaly, you should implement this per project. See https://github.com/pallets/click/issues/2207

Please add an option, e.g. --color=no and/or support https://no-color.org/

**Comment by bhirsz** [comment]
I'm OK with this change. It can support both env variable (NO_COLOR) and --no-color flag (and `color = false` in toml configuration file).

**Comment by bhirsz** [comment]
Should be implemented like https://github.com/MarketSquare/robotframework-tidy/blob/bbfcea389ab51e29a51571a3a82b56ac8f809da6/robotidy/cli.py#L220 but with default equal to value from env variable (like here https://click.palletsprojects.com/en/8.0.x/advanced/?highlight=envvar#:~:text=1%2C%20default%3D8080%2C-,envvar%3D%22PORT%22),-%40click.pass_context%0Adef ). Decorating with ANSI color is done here https://github.com/MarketSquare/robotframework-tidy/blob/bbfcea389ab51e29a51571a3a82b56ac8f809da6/robotidy/app.py#L126 so it should be easy to wrap it in if statement depending on `color` variable. 

I can implement it but I will label it is as good first issue since it looks good enough for first commiters. If nobody will take upon it I will do it later.

**Comment by bhirsz** [comment]
Released in Robotidy 2.2.
