### ISSUE TITLE
Errorneous documentation regarding InlineIf transformer

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-tidy#295]
Hi, as regards https://robotidy.readthedocs.io/en/latest/transformers/InlineIf.html:

1.
It reads:

_With following configuration Robotidy will transform all IFs to inline IFs if they are under 140 characters long:_
```robotidy --line-length 140 src.robot```

This does not function for me this way: there remains block-IF even when the resulting line would be about 100 chars long. I think there is 80-chars limit (see discussion on Slack on April 4), which is applied and is not documented. 

However, I would like Robotidy work as written in docs: when only global line_length is set, it would affect everything; but for particular transformers it could be overridden. :)

2.

There is a typo in the last example:
```robotidy --line-length 140 --configure InlineIf:line_length:80 src.robot```
The last ":" should be changed to "=".

**Comment by bhirsz** [comment]
Thanks for the report - most likely the issue is withing..building the documentation:
![image](https://user-images.githubusercontent.com/8532066/169704009-e871240e-b9ce-41c9-a376-114389abb4f8.png)

Currently 1.6.2 is live while it should be 2.3. Most recent version described the line-length option bit better. 

Hovewer there is typo in the example - I will fix it, thanks!

**Comment by bhirsz** [comment]
> However, I would like Robotidy work as written in docs: when only global line_length is set, it would affect everything; but for particular transformers it could be overridden. :)

That's how InlineIf worked at the beginning but then some people opposed saying that global limit is bit too lenient for InlineIf case (120 line length) and that's why it use separate value of 80. I need to think about this - most likely it should be discussed and decided on during style guide discussions that (I hope) will soon kick off.

**Comment by bhirsz** [comment]
Linked PR with typo fixes and rebuilded the online documentation and added warning if the doc version is not up to date:
![image](https://user-images.githubusercontent.com/8532066/169704935-1723b9e8-b51b-4d65-a599-b227f409525b.png)

**Comment by mnojek** [comment]
> Linked PR with typo fixes and rebuilded the online documentation and added warning if the doc version is not up to date: ![image](https://user-images.githubusercontent.com/8532066/169704935-1723b9e8-b51b-4d65-a599-b227f409525b.png)

That's great! Can we have it in Robocop as well? :)

**Comment by bhirsz** [comment]
> > Linked PR with typo fixes and rebuilded the online documentation and added warning if the doc version is not up to date: ![image](https://user-images.githubusercontent.com/8532066/169704935-1723b9e8-b51b-4d65-a599-b227f409525b.png)
> 
> That's great! Can we have it in Robocop as well? :)

Yes of course, it's actually fairly easy flag to set in the readthedocs so I just did it. For robocop due to the different theme the warning looks bit nicer:
![image](https://user-images.githubusercontent.com/8532066/170826127-3e37b480-bf4e-4b39-bc15-5923c1aae549.png)
