### ISSUE TITLE
NormalizeSeparators and other formatting could be optional on Documentation

### ISSUE THREAD

**Issue by levlist** [MarketSquare/robotframework-tidy#300]
Hi,

Our keyword documentation policy requires that beside the documentation itself the argument description as well.
But unfortunately, the NormalizeSeparators ruins our format.

An example:

Before format:

```
TEST_TC
    [Argument]    ${a}    ${long_arg}
    [Documentation]     Test Doc.
    ...
    ...    Arguments:
    ...    a:               Argument A
    ...    long_arg:        Argument long_arg.
   Test Case Body
```

After format:
```
TEST_TC
    [Argument]    ${a}    ${long_arg}
    [Documentation]     Test Doc.
    ...
    ...    Arguments:
    ...    a:    Argument A
    ...    long_arg:    Argument long_arg.
   Test Case Body
```

We use spacecount=4 and the correction itself is an extremely good feature, but for example, it could extend the selection argument with a documentation element as well, where the users could turn the separator normalization off on documentation if they want.

Thank you for your help and answer in advance!

**Comment by bhirsz** [comment]
Yes, in case of the documentation in most cases fixing the separator is probably not desired (with the exception of indent - first whitespace in the line). And there are actually two problems here:

1) Make NormalizeSeparator to skip documentation (or just fix indent)

2) Create transformer for documentation

In my opinion 2) would be really useful and with formatter for documentation we don't need to sorry about NormalizeSeparator breaking anything. I need to think what would be desired in the documentation formatting (and maybe allow few different types of documentation, configurable). We could achieve what you have in your first example done automatically by robotidy then.

Otherwise 1) should be easy to do as workaround for time being.

**Comment by levlist** [comment]
Both of them are good ideas.
The second opinion could guide the users to use or help how should look like documentation according to "standard" recommendations, like sphinx or Google docstring documentation. (Personally, the Google one is sympathetic for me.)
The first one I think is also useful if they are using a custom document format that is matching to none of the widely-spread documentation formats that you had in mind.
Or just simply they don't want to re-format/check their documentation by robotframework-tidy.

IMO the two ideas should complement each other.

**Comment by bhirsz** [comment]
I agree. On a side note I had some related discussion about "I don't want X to transform Y". For example someone wants to use an aligner transformer to align tokens into columns, but doesn't want to align documentation or lines with particular content. In some cases we have transformers that allow configuring what to transform/skip (``skip_types`` in AlignVariablesSection or ``sections`` in NormalizeSeparators). It could be a good idea to add a universal way of declaring what a given transformer should transform/format instead of doing this on the transformer level. This would work on top of current disablers (``# robotidy: off``). Examples:

robotidy --configure NormalizeSeparators:skip=sections=comments
robotidy --configure NormalizeSeparators:skip=settings=documentation,teardown
robotidy --configure AlignVariablesSection:skip=types=dict

It's a more complex subject that I will think about. For the time being I will just add an extra parameter to NormalizeSeparator (like ``skip_documentation``).

**Comment by levlist** [comment]
This universal way sounds great, thank you!

Thank you for the `skip_documentation` parameter until this universal way is ready.

**Comment by bhirsz** [comment]
Linked PR with ``skip_documentation``. It will be released in Robotidy 2.4 in the next few days. For other ideas mentioned in this post I will create seperate issues later and link it there.

**Comment by levlist** [comment]
Thank you for your help and quick support.

**Comment by bhirsz** [comment]
Closing - the issue was resolved in previous release and for other topics we have separate issues open.
