### ISSUE TITLE
[Bug] Extremely long dictionary definitions aren't consistent between runs

### ISSUE THREAD

**Issue by admorgan** [MarketSquare/robotframework-tidy#360]
Using the sample file included below the indention of the dictionary definition will bounce between column 8 and 21. The same thing does not happen when assigning non-dictionaries as can be seen with variable thing2. When trying to use this with CI, you can't commit the code because robotidy will always generate a different result.

```
*** Settings ***
Documentation       Demonstrates that robotidy can't make up its mind


*** Variables ***
&{sync modules}
...    over_the_top_of_reasonable_super_duper_really_Over_the_top_Really_Extra_ordinarily_long_key_1=value1
${thing2}
...    over_the_top_of_reasonable_super_duper_really_Over_the_top_Really_Extra_ordinarily_long_string_no_I_mean_really_really_long
```

**Comment by bhirsz** [comment]
I was thinking about it recently - that some transformers uses attributes that are recalculated only when read from the disk (so once). In your case it's probably "fight" between align variables and SplitTooLongLine - the first modify the position of the variable. But the node colend (used to determine if the line should be split) is not updated so the SplitTooLongLine is not triggered. In the second run coleend is updated so the SplitTooLongLine detect too long line and split it.

There are few solutions:
1) Use attributes that are dynamic (for example instead of colend just check the sum of the line length)

2) Reload AST model between runs. It will work for sure but I will heavily impact performance so I leave it for last resort.

I will go with 1). Also we need a way to detect such issues. We have a lots of tests but it covers acceptance testing for given transformers in isolation. We dont' have integration tests. It would be beneficial to have at least one test (it could acceptance tests test data) that would run all transformers twice over the sources and 1) it should not break 2) second run should not modify anything.

I will open extra issue for it later.

**Comment by bhirsz** [comment]
The issue lied somewhere else but it was close to what I found. Thanks for newly created e2e tests (I will link PR soon) it was easier to find.

Note that still there are some bugs left and some files will require few reruns until code "stabilize". This is because Robotidy does bit more than other formatters (such as black) and also fixes invalid syntax, sort code etc. This can change layout of the code and sometimes require 2-3 reruns until the code "stabilize". Then any additional rerun should not change the code.

But if after merging & releasing the PR there will be situation when the code change back and fort (so on 3rd..4th.. etc run it still keeps changing) it should be of course reported as a bug (thanks in a advance!).
