### ISSUE TITLE
Doc typo: NormalizeSeparators page - Ignored sections example typo

### ISSUE THREAD

**Issue by glueologist** [MarketSquare/robotframework-tidy#384]
Doc uses '**sections**' but example incorrectly uses '**section**':

### Ignored sections

You can decide which sections should be transformed by configuring 
**sections** = comments,settings,variables,keywords,testcases param:

robotidy --configure NormalizeSeparators:**section**=variables src
.....................................................................^^^^

**Comment by bhirsz** [comment]
Thanks! Since this kind of typo is not the first time I need to think of a way to avoid such problems. For example we can test the examples provided in the documentation - gather all configuration/run examples and run them in an isolated environment and check return status. Probably it'll take a bit more time than it's worth but it sounds interesting, I will think about it and open a new issue for it if needed.
