### ISSUE TITLE
Issue with AlignTestCasesSection:skip_return_values=True

### ISSUE THREAD

**Issue by tkopra** [MarketSquare/robotframework-tidy#386]
Hi

Following code breaking issues with AlignTestCasesSection (and probably also AlignKeywordsSection) with skip_return_values=True
![image](https://user-images.githubusercontent.com/106748650/182305496-44be4c83-f00a-4160-94b3-4d4548a3efc4.png)

Best Regards,
Tero

**Comment by bhirsz** [comment]
Thanks for reporting, it looks like severe bug (since it does break the code). I implemented the fix in the linked PR.

**Comment by bhirsz** [comment]
But the fix does it in a bit naive way - if the column with last return value overflows (there is no space for minimal separator left) it will use min separator. It looks like compact_overflow (and will look the same even for other overflow modes):
![image](https://user-images.githubusercontent.com/8532066/182384446-a344b921-cc26-4744-8b8d-4f3cde161686.png)

I can later think about implementing 'true' overflow handling for space between last return token (if we're using skip) and first data column.

**Comment by bhirsz** [comment]
Because with handle_too_long=overflow it should be:
![image](https://user-images.githubusercontent.com/8532066/182384828-bc68c06d-2a7d-4e60-a7a4-dbed6a7993e7.png)

ignore_rest and ignore_line are bit more problematic to define (since we're skiping the return values, then we're deciding to skip whole line because first token after return values does not fit immedietely in the column).

**Comment by bhirsz** [comment]
Since users who are using ``skip_return_values`` are doing it most likely for more compact view, I opted to retain the fix as it is. If there is request for it I will update handling the "overflowed" variables with ``handle_too_long`` mode instead of currently fixed compact_overflow for spacing right after return values.
