### ISSUE TITLE
For CI usege it would be nice to have possibility to return non zore exit code

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-tidy#42]
When running in CI, it would be nice to make robotidy to return non zero exit code if there is lint errors or warnings, so that it is easy to spot error in CI. But in the other hand when user is linting during development time, it would be nice to always return with zero exit code. This would allow run other lint tools with some script, like invoke. 

I am looking same sort of functionality as [Black](https://github.com/psf/black) has with `--check` command line flag: 
```
  --check                         Don't write the files back, just return the
                                  status.  Return code 0 means nothing would
                                  change.  Return code 1 means some files
                                  would be reformatted. Return code 123 means
                                  there was an internal error.
```

**Comment by bhirsz** [comment]
I've added it in linked PR. Right now it works like this:

if no files are affected and there are no errors, return 0
if there is at least one file that would be transformed or there is any error, return 1 (without transforming)
```
robocop --check  <src>
```

In the future I will catch errors separetly and give them other return code (for example 100). I could also return number of files that would be transformed - ie if 5 files need transforming, Robotidy would return 5 (up to 254 due to cli limitiations).

**Comment by aaltat** [comment]
Great work, thanks for speedy response. 

Hnmm, generally in CI, I care that was the return code zero or not. If there is non zero exit code, I will go look from CI logs what was wrong. 

Also some Git servers support sending annotations back to the pull request. Example CI run could tell back to pull request that file x has error z in the line 42. There is a simple rest api to communicate with the Git server and the needed thing from the lint tool is to output json file(s) from the lint errors.

**Comment by aaltat** [comment]
But because the original request is done, should we close this issue and write new one if need arrives?

**Comment by bhirsz** [comment]
Robotidy is more of formatting tool rather than lint tool (which would be Robocop) and I would rather use Robocop for PR annotations - although you can also use --diff together with --check (or --no-overwrite to get return status 0 but not overwrite files). --diff displays what changes would be done by Robotidy. It could be reused for annotations.

Yes I will close this issue after merging PR and we can open new one if there is need.
