### ISSUE TITLE
ReplaceRunKeywordIf sometimes add extra = char

### ISSUE THREAD

**Issue by jylind** [MarketSquare/robotframework-tidy#446]
Tested with robotidy 3.3.2.

We have keyword:
```
If Monitor Addresses Specified
    [Documentation]    Execute only if monitor information is configured.
    [Arguments]    ${kw}    @{args}
    ${data} =    Run Keyword If    '${MONITOR_IP_ADDRESS}'!='NOT_SET' and '${TRACEMON_PORT}'!='NOT_SET'
    ...     ${kw}    @{args}

```

After running `ReplaceRunKeywordIf ` on it, it becomes:
```
If Monitor Addresses Specified
    [Documentation]    Execute only if monitor information is configured.
    [Arguments]    ${kw}    @{args}
    IF    '${MONITOR_IP_ADDRESS}'!='NOT_SET' and '${TRACEMON_PORT}'!='NOT_SET'
        ${data} =     ${kw}    @{args} =
    ELSE
        ${data} =    Set Variable    ${None}
    END
```

There are two problems with this:

- It is missing the `Run Keyword` keyword when it is supposed to run the keyword in variable `${kw}`.
This might work in real run but definitely break the Robot dryrun. 
- It sometimes add this extra `=` char there after `@{args}`.

I guess the first problem is fine as how the transformer could know that it still needs to use that `Run Keyword` for the first argument. If it could that would be create.

The second problem might actually be a real problem. Maybe it shouldn't be there. Other thing about it is that sometimes it there and sometimes it goes away when rerunning robotidy (seen it some other cases where `Run Keyword If` is replaced).  

Might be related to this configuration line?:
```
NormalizeAssignments:equal_sign_type=space_and_equal_sign
```

**Comment by bhirsz** [comment]
Interesting case(s). The main issue there is that you have reason to use run keyword (because your keyword is in variable) and when its replaced to IF it will not work. So replace keyword if transformer should recognize if keyword name is actually variable and do not replace it to if.

And I'm not sure why it adds = at the end bust most likely after invalid transformation robot thinks that those two variables are actually return values and not keyword and keyword arguments. If the main issue is resolved it should not happen although I will see if I can make NormalizeAssigment to leave lines that have only variables alone.

**Comment by bhirsz** [comment]
Sorry for the delay. Managed to fix the issue - now whenever the keyword name looks like an variable, Robotidy will add "Run Keyword". It will not fix all possible edge cases with variables but it should cover your issue.
For '=' issue, this fix should make it go away. But I will look into NormalizeAssigment so it will not add '=' in such cases as extra measure.

**Comment by jylind** [comment]
No problem. Thanks for the fix.
Looking out for the next release then.
