### ISSUE TITLE
List enabled transformers

### ISSUE THREAD

**Issue by jylind** [MarketSquare/robotframework-tidy#464]
There should be a way to list enabled transformers.

One option would be to add another column to output of --list command f.g. just  `Enabled`
that would list the status after configuration is taken into account.

**Comment by jylind** [comment]
Yes, that sound about right.👍

- Having default values is great way for checking what might need enabling/disabling for my own use.
- Having status reflecting my configuration provides easy way to verify it
- If we/you want to play with colors then changed values could be shown in different color.

Well, I tend to use this kind of list (both robotidy & robocop) is in CI runs. Having the printout in CI output provides an easy way check what configuration, in fact, was in place when something failed (or did not fail).

**Comment by bhirsz** [comment]
I have figured out the first part (using configuration in ``--list``). Now it will use white colour for default, and magenta (current color for disabled transformers) for modifed ones. 

Default output (on Windows):

> robotidy --list
![image](https://user-images.githubusercontent.com/8532066/219883717-d9d079c0-3a85-4517-9061-c967ab76f37d.png)

> robotidy -c configure Translate:enabled=True --list
![image](https://user-images.githubusercontent.com/8532066/219883746-c2754a0a-8847-44c5-a49b-d1dee098ea42.png)

> robotidy --transform Translate --list
![image](https://user-images.githubusercontent.com/8532066/219883765-48bb06a3-7ede-4e65-b856-ac0ff991d127.png)

**Comment by bhirsz** [comment]
For the second part (and main topic of this issue), the click 8.+ version introduces optional values. I have decided to bump minimal required version of click (from 7.1.3) to get this feature. 

With this it is possible to filter our results:

![image](https://user-images.githubusercontent.com/8532066/219884531-f009cb7f-4f85-451c-8e07-9db70cc031e8.png)

**Comment by bhirsz** [comment]
FInal note - the ``--list`` obviously will take into account configuration from the config files. Now I need to add various tests for this feature. It should be part of the next release (which I'm planning for tommorrow). 

I can tweak this option in the future if there are any additional suggestions or bugs.

**Comment by jylind** [comment]
Just couple things to remember.

Usually in CI there are no colors (but the main thing to get is what are the active transformers).

As it takes into account the config the list should also contain custom (users own) transformers.

**Comment by bhirsz** [comment]
The color are just addition - but I agree that without the color it's impossible to see if the original status was overwritten by configuration. I will add "*" to enabled status to further denote such cases, so it is visinle even without colors. 

As for custom transformers, you're right, I completely forgot about them! The code is designed in a way that it should be already supported or easy to add support but I need to test it. It's actually interesting because it's clear for me people are creating they own rules for Robocop but I have not heard about custom transformers that much. I hope though they are in use and I will provide support for them. Thanks!

**Comment by jylind** [comment]
The thing is that, well, first I had this feature request to allow underscore as first char in keyword name to visually mark "private" keywords in RenameKeywords but soon realized that it not enough.

We need the following:
- Remove underscore
- Make words title case
- Handle embedded variable "our way"

The last thing is the difficult one. We have a format how to use embedded variables. And they may contain underscores and all lowercase letter. they need to be detected and excluded from the transformation.
So we may need to customize what you have already done. And I will need to learn that.
So happy debugging ahead

It would help, though, if there would be a bit more words on how those work😉

**Comment by bhirsz** [comment]
Our transformers were designed on top of the Robot Framework Model Transformer. That's why there isn't much of the documentation (except https://robotidy.readthedocs.io/en/stable/external_transformers.html), Besides various optional features from the robotidy (like skipers or disables, formatting config etc) the transformer code is just Python code and Robot API. However I know that learning the Robot Framework API/model takes time and there are various special edge cases or problems (RF is after all quite flexible). What helps me is follow TDD approach. I first create some skeleton of the transformer, create basic tests and run them and debug to see what Robot model of given part of the code looks like etc.

You can start by using ``RenameKeywords`` transformer and its tests (https://github.com/MarketSquare/robotframework-tidy/blob/main/tests/atest/transformers/RenameKeywords/test_transformer.py). Select given test, put breakpoint in the code and see what you will get. The ``RenameKeywords`` has bit of complicated code because of all possible edge case it covers. In your case if you want what you want you might to use lot less code. For instance the lines with ``VariableIterator`` parse the embedded variables in the code and may be useful for you. I'm always happy to help and if you have any questions I will answer. And I will try to extend our documentation on the topic.

Btw thanks to you I have found some leftover debug code in the ``RenameKeywords`` :D Such as:
```
        if value.strip() == "${keyword}":
            print()
```
I will clean it up.
