### ISSUE TITLE
Robotidy adds extra new line at the feed back at the end of test suite file

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-tidy#47]
If my test looks like this (Test is 4 lines long):
```
*** Test Cases ***
Values Are Equal Fails
    Log   1111
```
When I run `robottidy  atest` command (pointing to folder), then formatted file will look like this
```
*** Test Cases ***
Values Are Equal Fails
    Log   1111

```
The test comes 5 lines long. I think that is not correct and there should be only one empty line.

**Comment by bhirsz** [comment]
Thanks for pointing that out - it was working if the *** Settings *** was at the end of file (that's what we used in our atests) but not with Test Case / Keyword because RF uses bit different approach for empty line handling (basically, if there is empty line in settings it's separate entity, where in Test Case / Keyword section it's grabbed by Keyword / Test Case definitions -> so to remove it, we need to go inside definitions). 

Fixed in attached PR
