### ISSUE TITLE
Preserve formatting in NormalizeTags transformer

### ISSUE THREAD

**Issue by levlist** [MarketSquare/robotframework-tidy#472]
Hi,

I don't know is it a feature or bug, but the NormalizeTags merges the multi-line [Tags] part into one line and the comments are moved to the end of the line.
Based on the documentation it should normalize only the cases, but there is no other information about line (and comment) handling.

Executed command:
robotidy -t NormalizeTags --no-overwrite --diff MyTestSuite.robot

Result:
![image](https://user-images.githubusercontent.com/10905822/220859258-8a6a82ad-28bf-4552-9e26-5482144115e8.png)

It would be nice an argument for example: "preserve_format=True" which should normalize only and only the tags (ignore the comments), preserves the multi-lines, and should not separate tags from the comments.

Note:
The random upper cases in the tags are only for testing purposes, whether this line merging and comment relocation breaks the normalization or not.

**Comment by bhirsz** [comment]
It does recreate while tags node do the original formatting is lost. I agree that we should add way to keep formatting, it should not be be hard to implement. I will add it to my backlog.

**Comment by bhirsz** [comment]
I have already implemented it. When the PR is merged this issue will auto-close but this feature will be release with next release (probably by the end of the week in 3.5.0). 

With ``preserve_format`` the format will be preserved but ``NormalizeTags`` will only normalize tag case, and duplications will not be removed (since removing duplications would break the format).

**Comment by levlist** [comment]
That was extremelyfast. :-)
Thank you very much.

**Comment by bhirsz** [comment]
Change is now live in Robotidy 3.5.0.
