### ISSUE TITLE
Enhancement: Update config parsing to better support larger file structures

### ISSUE THREAD

**Issue by Ga22be** [MarketSquare/robotframework-tidy#506]
## Background
The current config file parsing is missing some key features for users with larger code-bases. When robotidy searches for a config file today, it looks upward in the directory structure until it either finds a config file, the system root, or it finds a _.git_ directory, see [docs](https://robotidy.readthedocs.io/en/stable/configuration/config_file.html#configuration-file). This is based on the following assumption:
> Robotidy will also look by default for pyproject.toml file starting from directory of the source(s) passed on the command line and going up to parent directories. It stops when it finds the file or it finds root of the project (determined by existence of .git directory) or root of the file system.

**_NOTE:_**  According to the source code [here](https://github.com/MarketSquare/robotframework-tidy/blob/d5f8cbf30039bd875780ee5830691f05f108439f/robotidy/files.py#L18), there is also the option of naming the config file _robotidy.toml_, though I can't find any reference to this name in the docs.

This assumption has a flaw which makes this functionality frustrating for some use cases. While ``git`` is indeed a very common tool for distributed version control, it is not the only way developers work with "projects". For example, in bigger projects it is not uncommon to use tools like [git-repo](https://gerrit.googlesource.com/git-repo) or even just [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules). Using these tools one might create a project, which we will assume to use the same code standards, containing several git repositories (signified here by the .git directory). With the current implementation this means that if a test developer places a robotidy config file in their project root, any run of the tool performed inside one of these directories will not see the config file because it's above the assumed project root (.git).

## Suggested design
I would like to suggest an alternative approach to config file searching. I have used [Clang-Tidy](https://clang.llvm.org/extra/clang-tidy/) for C/C++ code formatting before and I quite like the way that they do it. See the heading "Configuration files:" in the link above.

> Configuration files:
  clang-tidy attempts to read configuration for each source file from a
  .clang-tidy file located in the closest parent directory of the source
  file. The .clang-tidy file is specified in YAML format. If any configuration
  options have a corresponding command-line option, command-line option takes
  precedence.

``Clang-Tidy`` always tries to apply the config file closest to the file being formatted. This means that if there is no config file in the same directory as the source file, then it will look upwards in the directory structure to find the closest config. This approach would solve the current issues with the robotidy design, by completely ignoring the existence of _.git_ directories. Another great feature would be that a run of the tool on the complete project could format different files differently depending on what config is the closest to their respective directory. 

![robotidy-config-design](https://user-images.githubusercontent.com/6941738/229555156-3fbf6bb4-c67a-4275-a012-b8225aa9a4bb.png)
Lets imagine the file structure drawn above, _repo-project_ and _submodule-project_ are two different example projects. _submodule-project_ has a config defined in it's project root, _repo-project_ does not.

If one was to run robotidy in the _submodule-project_ directory it would apply the config in that same directory to all files in all of the subdirectories. If one instead was to run robotidy is _subdirA_ it wouldn't find a config in that directory and instead look upwards, finding the config in _submodule-project_, unlike today when default config would be used.

If one was to run robotidy in the _repo-project_ directory then _subdir1_ would use the config file in that same directory, while _subdir2_ and _subdir3_ would instead use the config found in the _dev_ "global" config. 

## Side notes
1. ``Clang-Tidy`` uses the file naming _.clang-tidy_ for its config files, much like ``git`` uses _.gitignore_ and such file naming schemes. This is a very Linux/Unix centered way of doing it, but also very convenient. I myself initially assumed that ``robotidy``, based on the naming, would be very similar to ``Clang-Tidy`` and named my config _.robotidy_ before I had properly read the manual. I would however suggest, based on the existence of the robotidy.toml file and the possibly non-trivial and backwards breaking changes that this request entails that the config file changes name to _.robotidy_ or atleast that it be added as an option. It would blend in better with [other tool config files](https://wiki.archlinux.org/title/Dotfiles).
2. ~~``Clang-Tidy`` disables all default "checks" (sort of like transformers) when reading configuration from a file. This makes the configuration of the tool simpler since you always start from a clean slate, but it also makes the output more predictable if the tool is updated and new defaults were to be added. I would suggest either that the defaults are disabled if a config file is read, or if that is to radical to instead add a CLI option **--no-defaults** which would be possible to specify in the config file as well.~~

**_Edit:_** It seems I had misinterpreted how default transformers were handled when specifying specific transformers under "transform" in a config file. Hence no changes should be needed in this area.

**Comment by bhirsz** [comment]
Regarding ``robotidy.toml`` - this is deprecated filename used before ``pyproject.toml``. ``pyproject.toml`` is common standard configuration file for Python application and that's why we decided to change it - but we left the ``robotidy.toml`` in the source code for compatibility reason.

It is interesting idea and it's good that you have created the issue (we discussed it in Slack but I misunderstood your request). It would require quite a big code change in parts related to config parsing. It isn't easy because of the click (I find it easier to work with config files with argparser). But implementing it may be useful for the users and by the looks of it it shouldn't be backward incompatible - all current users who just use one common config file will be still handled in a same way.

I'm only worrying about the performance - since we would need to look for configuration file for every file formatted. I need to remember to use caches (for example to find the config file for files in the same directory, or don't load the same configuration file twice).

Looking at the design I would also need to redesign cli parsing a bit. Currently we first look for configuration file, load it and supply it as defaults to cli options, who then can overwrite it. 

---

1. I'm fine with having additional config file name ``.robotidy`` - but for simplicty sake the format would need to be the same as ``pyproject.toml`` (so ``too.robotidy`` section with config).

2. I'm not sure about this option. If you want to disable all defaults you just need to run something with ``--transform``. That way every default transformer will be disabled and only transformers included with ``--transform`` will be run. Definitely disabling all defaults when reading the config file is too radical and would be bothersome for all current users (most users just configure selected few transformers and keep to defaults). I can think about ``--no-defaults`` option though - programmatically it is easy to achieve, but I need to think if it's needed given ``--transform`` functionality.

**Comment by Ga22be** [comment]
Good to know about the ``robotidy.toml`` deprecation.

Regarding the performance I don't see that as a major issue. As you pointed out in a roundabout way, you would not need to parse the config for every source file, but for every directory where one or more source will be processed as the proximity will be the same for every directory.

Regarding the backwards compatibility, if some inconsistencies were to arise, simply limiting this new parsing behavior to ``.robotidy`` files would solve that issue.

If the request is to big to do all at once I would suggest splitting it in two parts, first removing/allowing the user to disable the .git root matching, and secondly to update the config parsing to use the proximity approach that ``Clang-Tidy`` uses.

------------------------------------------
1. That sounds ok, but I don't think it would be to hard to remove the ``tool.robotidy`` encapsulation since it is simply stripped when loaded anyway [here](https://github.com/MarketSquare/robotframework-tidy/blob/b6893a2451fb79fa05a37a37cf2c1b994de6d816/robotidy/files.py#L72). So a different implementation ``def read_dotfile_config(path)`` would just need to parse the file but not strip that part. I think it would be confusing to have pyproject formatting of a non-pyproject file, toml format should still be fine tho.
2. I have experimented a little bit and I think I had initially misunderstood when default transformers were used. I was under the impression that default transformers would still apply even if one were to specify an arbitrary number of transformers in the "transform" field of the config file. After some testing with different config files and the CLI option ``--list`` I have however concluded that the current behavior is as I wanted it. I.e. as soon as a transformer is specified under "transform" all default transformers are disabled, so no changes should be required. :+1:

**Comment by bhirsz** [comment]
Yes, it shouldn't affect the performance that much if it's implemented correctly.

There also should not be problem with backward compatibility - now I see that any current user will have their single configuration file detected and taken into account with the new design as well. 

I agree on splitting the feature, I will include ignoring .git in the next, small release and work on this feature in the meantime.

And for later point:

1. I also agree, since it's new config file name ``.robotidy`` we can remove ``tool.robotidy`` section and document it properly in the documentation and it should be fine. It doesn't require much work.

**Comment by bhirsz** [comment]
Update - I'm working on this since last week and I've just reached the MVP. The MVP covers everything you wanted. Now I want to focus on fixing/adding new tests, documentation, refactors (I had to drastically change some of core classes). However it's on good track.

**Comment by bhirsz** [comment]
Linked PR that implements this feature. I will add support for ``.robotidy`` in a separate PR

**Comment by bhirsz** [comment]
Support for loading multiple configuration files & ".robotidy" file support were released in Robotidy 4.2.0. Closing the issue
