### ISSUE TITLE
Add Featue Transform : Sort Keywords and Enforce  Title Name convetion

### ISSUE THREAD

**Issue by IlfirinPL** [MarketSquare/robotframework-tidy#52]
To allow to sort keywords by name and convert to title case ex.

Before
make object with features
create something 

After
Create Something 
Make Object With Features

**Comment by JaPyR** [comment]
@bhirsz are you interested in PR with new transformation that cover part related to sorting keywords?

**Comment by bhirsz** [comment]
@JaPyR I'm always interested in PRs ;) I'm not sure if people would want to sort their keyword definitions by default - but we can add this transformer and people would just not run it if they don't need it. 

And renaming keyword should be separate transformer from sorting (because every transformer should have single responsiblity if possible).

**Comment by Zeckie** [comment]
Is this issue just for keyword definitions? Or will it also update where keywords are used (such as in tests)?

**Comment by bhirsz** [comment]
@Zeckie PR #67 introduced transformer for sorting out keywords - and it only updates the keyword definitions. I'm going to make this transformer as non-default (so it would be only executed when configured explicitly) because I believe most people would want to keep their original order of keywords (in ``*** Keyword ***`` section).

This issue also mention converting to title case - if it would be implemented it should update keyword name in all places.

**Comment by katjie** [comment]
Hi @bhirsz

I am particularly interested in converting the keywords to title case, and this is the only issue in which I could see this mentioned. Is there an update on if this will be included in a future version of robotidy?

**Comment by bhirsz** [comment]
@katjie It's "somewhere in the planning". The biggest issue is dynamic nature of keywords in Robot Framework and embedded variables, ie if it's definition:
```
Keyword with ${var} variable
```
and this is call:
```
Keyword with string variable
```
We would not want ``string`` ``${var}`` to be transformed to ``String``. 

But since we already have Sort Keywords working as non default transformer (as: it's only transforming files if people enable it) we can also create another non default transformer such as ConvertKeywordsToTitleCase that would perform this operation. If there will be issues ie transformer replacing embedded variables values, people are not forced to use this particular transformer (since it'll be non default).

It should be easy to implement and soon ready. But of course the more data I will receive now the more complete transformer will be. I think this transformer could transformer both keyword and test cases names, but with switch that enables to switch between title case (Title Case) and capitalization (Capitalized case):
```
keywords - titlecase(default),capitalize
test cases - capitalize(default),titlecase
```
I can create seperate issue for it where you can put your comments if you have other needs from this feature (ie extra configuration).

**Comment by bhirsz** [comment]
I added two transformers (RenameTestCases and RenameKeywords) that will be part of the next release. Details in linked issue. We can now finally close this issue :)
