### ISSUE TITLE
NormalizeTags:normalize_case=False does not work for .resource files

### ISSUE THREAD

**Issue by Apolayo27** [MarketSquare/robotframework-tidy#539]
In my project we manage the keywords in .resource files and in the .robot the scenarios with their tags, when --transform NormalizeTags:normalize_case=False is applied in the .robot, it makes the correct formatting, but when it is applied in the .resource for formatting it does not work.

**Comment by Apolayo27** [comment]
Hello I show you a screenshot of the execution of robotidy with --transform NormalizeTags:normalize_case=False, which does not make any improvement in the spaces e.g. @bhirsz 

![image](https://github.com/MarketSquare/robotframework-tidy/assets/44474459/1ace234c-3df6-4448-b46f-9edd041b6e87)

**Comment by bhirsz** [comment]
Ah, I did type down your screenshot and I have tried it (and it works) but now I realized where the problem lies: in the use of ``--transform``.

Transform is used to selected transformers for formatting. It works the same as ``--include`` in Robot Framework - only transformers with ``--transform`` will be executed. In your case only ``NormalizeTags`` will be run. ``NormalizeTags`` is enabled by default so no need to select it, but if it were the disabled by default transformer (for example ``RenameVariables`` you can enable it on top of default ones using enabled parameter:

```
robotidy --configure RenameVariables:enabled=False src
```

In you case, if you want to configure normalize_case to False you can:
```
robotidy --configure NormalizeTags:normalize_case=False <src>
```

It can be later added to configuration file (which is loaded by default if placed in the parent directory):

```
[tool.robotidy]
configure = [
    "NormalizeTags:normalize_case=False"
]
```

**Comment by Apolayo27** [comment]
great, it worked perfectly for me, thank you very much @bhirsz
