### ISSUE TITLE
AlignVariablesSection:min_width is not using spacecount

### ISSUE THREAD

**Issue by tkopra** [MarketSquare/robotframework-tidy#605]
Hi!

I upgraded to 4.6.0 from a bit older version and noticed that Variables section started to align differently. Looks like version 4.5.0 changed how AlignVariablesSection:min_width works and introduced AlignVariablesSection:fixed_width which is same as old behaviur. That works for me. But I believe there is a bug in the new AlignVariablesSection:min_width. It does not obey the spacecount and is always using 4 as minimum spaces.

See attached configuration file and test file where variables section is aligned differently than test cases. I was expecting same (tighter) alingment for both.

[variables_section_align_issue.zip](https://github.com/MarketSquare/robotframework-tidy/files/13704502/variables_section_align_issue.zip)

**Comment by bhirsz** [comment]
Yes, I see that I'm using fixed separator instead of configured one. I will fix that. I have also noticed that AlignVariablesSection first round the length to the closest multiply of four and then add 4 as separator. Now it will just round (token length + minimal separator) to closest multiply of four, for example:

Variable with length 33 waswas rounded to 36 and then +4 = 40 width
Now such variable with default separator: (33 + 4) rounded will still give 40. But with configured separator, ie 2: (33 + 2) rounded gives us 36.

This already make the output bit more concise. There will be additional changes in separate PRs as well, most likely I will allow to ignore too long tokens (kinda max_width) and other changes from open issues.

**Comment by bhirsz** [comment]
After my changes, it appears that your example code is aligned in the same way:

![image](https://github.com/MarketSquare/robotframework-tidy/assets/8532066/5c7409db-61c7-4242-ae9e-48e169b9f764)
