### ISSUE TITLE
[Documentation] is not changing to multi-line

### ISSUE THREAD

**Issue by ArekKuczynski** [MarketSquare/robotframework-tidy#615]
Hello,
If the [Documentation] section is longer than 120 characters, it will not be split.  For example:
```
[Documentation]    This is the first line of short and simple documentation. This is a continuation of the short and simple documentation.
```

However, when i add `def visit_Documentation(self, node):` function in SplitTooLongLine.py file it will look like this:
```
[Documentation]
    ...    This is the first line of short and simple documentation. This is a continuation of the short and simple documentation.
```
Shouldn't it be more separated? What do you think?

**Comment by bhirsz** [comment]
Documentation is not formatted on the purpose. Users usually create it manually and fill it with some sort of information (like argument types and description) according to chosen format. If we would split it we could mess with it by mistake. 

In your example you have documentation node with one token. You may notice that we dont split tokens - we just reaarange their positions (again, to not mess with people code too much). For example keyword call can have two arguments, one return variable and comment. Including keyword name it is 5 tokens plus separator tokens between them. When we find the line containing them is too long we just 'move' tokens around. If for example keyword argument is 200 characters long we can't really split it in half since we would break the code. We use the same principle for handling documentation. 

However splitting documentation is possible and is quite easy to achieve. Thats why you may want to implement it as custom transformer. If you dont want to preserve format and emtpy lines the easiest option is to collect all values in documentation mode, then split it on whitespace create lines up to character length. Create documentation token for each line and then create documentation node from those tokens. 

I'm in the middle of some bigger changes in Robocop / Robotidy so I'm busy right now but if you want I can add some pseudo code examples in this issue later (in a week/two).

**Comment by ArekKuczynski** [comment]
Thank you very much for your help and reply. I had some doubts before, but now everything is clear. You don't need to add additional examples, I already understood everything. Thank you!
