### ISSUE TITLE
RenameVariables adding extra underscore

### ISSUE THREAD

**Issue by jyligehc** [MarketSquare/robotframework-tidy#692]
Using robotidy 4.11.0, RenameVariable with default settings foollowing happens with variables in `Variables` section:

```
*** Variables ***
-${random_seed} =    ${None} 
+${RANDOM_SEED}_ =    ${NONE}
```
so the underscore after variable and before equal sign should not be there.
Also, maybe the `${None}` should not be updated?

Other minor corner case might be numeric (true/false) values where I would like to retain the original value:
`${0b1011}` `{0o10}` `${0xFF}` `${True}`

**Comment by bhirsz** [comment]
Thanks - I will check it out. We're due to release so it may be already fixed.

I can add ``${None}`` to ignroed by default. There is ``ignore_case`` paramater that allows to ignore (do not update) case of selected variables. By default its ``${\n}`` only. I may add ${True} and ${False} (it looks better than ${TRUE} etc) but for other names I will leave it to the user. Hovewer for numeric values I need to think about some generic way of ignoring them

**Comment by bhirsz** [comment]
I can confirm it's a bug - ``${return} = `` will be converted correctly for other sections but does not work for ```*** Variables ***``. I will fix it & add more tests
