### ISSUE TITLE
Dependency updates

### ISSUE THREAD

**Issue by Houbein** [MarketSquare/robotframework-tidy#725]
Currently Tidy requires tomli version 2.0.2, which is 3 months old, and rich-click 1.8.3, which is 4 months old. 
Please update these. 
More broadly spreaking, it is not a good practise to require specific minor versions of dependencies, please limit yourself to only fixing major versions of dependencies.

**Comment by bhirsz** [comment]
Thanks for pointing it out. Unfortunately we had situations were fix or minor version of dependency introduced some bugs. Thats why we are keeping it to specific version. However we should automatically update and release on dependency update, I will look into it.

**Comment by bhirsz** [comment]
Our dependencies are managed by Dependency Bot. Unfortunately there was invalid configuration (path to file instead of path to directory with dependencies) and it caused us to not have any updates in dependencies for some time. I have fixed (for robocop as well) and next update will have updated dependencies. thanks!
