### ISSUE TITLE
make SplitTooLongLine to split long lines in variables section

### ISSUE THREAD

**Issue by adrszad** [MarketSquare/robotframework-tidy#81]
I have a variables like this:
![image](https://user-images.githubusercontent.com/17517440/120497393-a5ee6a00-c3be-11eb-80d5-08c856ea7331.png)
which is not split by SplitTooLongLine transformer, it would be useful to have this option for some lengthy lists etc

**Comment by bhirsz** [comment]
Hi, thanks for the issue - and sorry for this delay! I was thinking about how it should work. Seeing line like this:
```
@{someList}=                     Example 1                                 Example2
```
if `SplitTooLongLine` would touch this line it would first try to fit it in line line using standard separator:
```
@{someList}=    Example 1    Example2
```
in that case it wouldn't split arguments (and we would lose the alignment from previously run AlignVariablesSection). 
Otherwise if variable doesn't fit ie:
```
@{someList}=    Loooooooooooooooooooooooooooooooong value    Loooooooooooooooooooooooooooooooong value2
```
it would split to multilines:
```
@{someList}=    Loooooooooooooooooooooooooooooooong value
...      Loooooooooooooooooooooooooooooooong value2
```
(which is fine - and could go with one argument per line for such cases). 

So the problem is with `AlignVariablesSection` that goes over allowed character count. Maybe we should implement it in such 
way that if after aligning the line we're above allowed character count, it should split it to next line automatically?
Of course there are deeper design decision in the background (so far I tried to have transformers fully autonomic but it's not possible in this case).

**Comment by ealap** [comment]
Maybe we could also just have an option to split a variable definition by every element and put them on a new line

Before
```
*** Variables ***
&{USER_PROFILE}                   name=John Doe                            age=12                            hobby=coding
@{VERY_LONG_VARIABLE_NAME_CONTAINING_FRUITS}             apple    banana    pineapple    tomato
```

After
```
*** Variables ***
&{USER_PROFILE}
...    name=John Doe
...    age=12
...    hobby=coding

@{VERY_LONG_VARIABLE_NAME_CONTAINING_FRUITS}
...    apple
...    banana
...    pineapple
...    tomato
```

Similar to what `SplitTooLongLine:split_on_every_arg=True` does for keywords, and maybe call it `split_on_every_value` for variables.

**Comment by MoreFamed** [comment]
I'd like SplitTooLongLine to split every long line, if possible. E.g., to split
`[Documentation]   Very long line with docs`
and so on...

**Comment by bhirsz** [comment]
Linked PR that adds spliting too long values. It should be part of the 3.0 release (planned for the next week). Splitting other too long stuff (settings, docs etc) will be added in the future releases.
